return {
  -- "samodostal/image.nvim",
  -- requires = { "nvim-lua/plenary.nvim" },
  -- dependencies = {
  --   { "m00qek/baleia.nvim", tag = "v1.3.0" }, -- color support
  -- },
  -- config = function()
  --   require("image").setup({
  --     render = {
  --       min_padding = 5,
  --       show_label = true,
  --       show_image_dimensions = true,
  --       use_dither = true,
  --       foreground_color = true,
  --       background_color = true,
  --     },
  --     events = {
  --       update_on_nvim_resize = true,
  --     },
  --   })
  -- end,
}
